### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by obonhamcarter** [ReadyResearchers-2023-24/cis-600-f2023-610-s2024-senior-thesis-pkelly55#9]
Hi Peyton,

Your work was very impressive. I offer several suggestions below that you may consider to implement.

## Versions of Libraries

In the thesis document, there are softwares mentioned that are used to build your project. It is important to list all the version numbers of the libraries in this work, including the version of Docker, Python and Django. This is because each library of your work is likely to evolve in the future and will require some extra attention, or coding on the part of the system administrator who will install your project with future-software.

## Code Blocks

In the Methods of Approach Section, there is discussion about setting up the virtual environment in Python with an installation of Django. While the necessary commands to install this software are provided in the text, they may not be conveniently found by the reader. To assist the reader in locating the code, I recommend that all commands (Python, Django, Docker and others) be located inside code blocks where the commands are clearly visible and described with comments. Providing code blocks can assist readers to more readily grasp the concepts being presented and apply them in their own work.

For example,

``` bash
$ python3 -m venv env # Build virtual environment
$ source env/bin/activate # start working session
(env) $ pip install "Django==2.1.*" # install Django library
```

Researchers and developers often rely on methods such as yours, and others which are outlined in academic papers to replicate setups, install software libraries, execute software and /or build upon existing work. With conveniently-located code blocks, readers can quickly identify the specific commands or techniques being described, to reproduce the work.

## Virtual Environment: types and technologies

In the Methods of Approach Section, Docker is mentioned as providing a solution for building a virtual environment. It might be necessary to spend some time to discuss what Docker is as a technology, and to introduce the differences between its virtual environment to the one that is created by Python's `venv` option. This will provide the reader with a better understanding of the types of security that your project is able to provide.

### Discussion for Code Blocks

You might want to consider rewriting parts of the Methods of Approach Section to read more like a tutorial where the code blocks are mentioned. This type of text would assist the reader to place the commands _when_ and _where_ they are necessary as they implement the project on a local machine.

## Minor Changes

+ Citations to references in text
  + Many of the citations have been incorrectly formatted in the text where the reference number appears after the period of a sentence. The number of the citation is to follow the fact within the sentence and before the period. See the example below.

  `Django ships with SQLite preinstalled [1].`

+ Some of the titles of headers and the thesis have lower case letters where they ought to be uppercase.
+ Page 23 of the Methods of Approach section is largely black. Could the figure on the next page be moved somewhere else to make less blank space on the page?
+ The captions of many of the figures require more detail. For example Figure 4 concerns a very important result of the project, yet there is not much detail in its caption to describe it. The text of Figure 3 is hard to read, and could be omitted after a short discussion in the text. Could Figure 3 be replaced with another chart or plot?

Please let me know if you have any questions over the above ideas and I would be happy to discuss them further with you.

Much thanks,
OBC

**Comment by pkelly55** [comment]
I have added version numbers to the packages that I felt were the most crucial to replication success. I added a piece of how docker is used and explaining what docker is. Citations have been fixed and so has the title capitalization. I removed the hard to read figure and added more descriptive naming conventions to the charts that have stayed.
